# Generated by Django 4.2.4 on 2023-09-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='imageUrl',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
