# Generated by Django 4.2.4 on 2023-09-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.image')),
            ],
            bases=('products.image',),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryimage'),
        ),
    ]
