# Generated by Django 4.2.4 on 2023-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.CharField(max_length=255),
        ),
    ]
