# Generated by Django 4.2.4 on 2023-09-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_saleitem_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
